name: Pull request
on:
  pull_request:
    branches:
      - main
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7.0"
          bundler-cache: true
      - run: bundle exec rubocop
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.7.0", "3.2.1"]
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Bundle audit
        run: bundle exec bundle-audit --update
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake test
